spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  dataSource:
    url: jdbc:postgresql://localhost:5432/linker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver